import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GolbalLayout from "./_context/golbal-layout";
import Providers from "./_progressbar/progressbar";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "./_theme/theme-context";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          <TooltipProvider>
            <Providers>
              <GolbalLayout>
                {children}
                <Toaster />
              </GolbalLayout>
            </Providers>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
